/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pacientes;

import Conexion.ConnectionPool;
import StaffMedico.Buscar;
import InicioSesion.inicioRecepcionista;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DELL
 */
public class pacientes_interfaz extends javax.swing.JFrame {

    /**
     * Creates new form pacientes_interfaz
     */
    ConnectionPool conE = new ConnectionPool();
    //Conexion conE = new Conexion();
    Connection conetE;
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;
    int idE;
    TableRowSorter trsfiltro;
    String filtro;
    PacienteDAO pacienteDAO = PacienteFactory.methodsDAO();

    public pacientes_interfaz() {
        initComponents();
//        mostrarpacientes();
        setLocationRelativeTo(null);
        mostrarpacientes();
    }

    void mostrarpacientes() {
        String sqlConsult = pacienteDAO.mostrarPacientesSQL();
        try {
            //conetE = conE.Conectar();
            conetE = conE.getConnection();
            st = conetE.createStatement();

            rs = st.executeQuery(sqlConsult);

            Object[] pacientes = new Object[8];
            System.out.println("s");
            modelo = (DefaultTableModel) this.TablaPacientes.getModel();
            while (rs.next()) {
                pacientes[0] = rs.getString("id_dni");
                pacientes[1] = rs.getString("apellido_paterno");
                pacientes[2] = rs.getString("apellido_materno");
                pacientes[3] = rs.getString("nombres");
                pacientes[4] = rs.getString("eps");
                pacientes[5] = rs.getString("fecha_nacimiento");
                pacientes[6] = rs.getString("genero");
                pacientes[7] = rs.getInt("telefono");

                modelo.addRow(pacientes);
            }
            TablaPacientes.setModel(modelo);
        } catch (SQLException e) {

        }
    }

    public void registrar() throws SQLException {
        //Connection con1 = new Conexion().Conectar();
        Connection con1 = new ConnectionPool().getConnection();
        paciente_modelo uno = new paciente_modelo();
        if (this.dni_reg.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Uno o mas campos estan vacios. Favor de llenarlos.");
        }
        String sqlConsult = pacienteDAO.registrarPacientSQL();
        
        try {
            PreparedStatement psd = (PreparedStatement) con1.prepareStatement(sqlConsult);
            psd.setString(1, this.dni_reg.getText());
            psd.setString(2, this.nomb.getText());
            psd.setString(3, ap.getText());
            psd.setString(4, am.getText());
            psd.setString(5, this.fn.getText());
            psd.setString(6, this.sexo.getText());
            psd.setString(7, eps.getText());
            psd.setString(8, telef.getText());

            int n = psd.executeUpdate();
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "Registro Guardado");
            }
        } catch (SQLException e) {
            System.err.print(e.toString());
            JOptionPane.showMessageDialog(this, "Ocurrio un error inesperado.\nFavor comunicarse con el administrador.");
        }
    }

    public void buscarpaciente(String buscar) {
        this.TablaPacientes.setModel(modelo);
    }

    public void buscar(String dni) {

        DefaultTableModel modelo = pacienteDAO.buscar(dni);
        TablaPacientes.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        dni_buscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomb = new javax.swing.JTextField();
        ap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        am = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dni_reg = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sexo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        eps = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        telef = new javax.swing.JTextField();
        hc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        botonRegresar_Recepcionist = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPacientes = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 645));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dni_buscar.setPreferredSize(new java.awt.Dimension(284, 35));
        dni_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dni_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(dni_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 177, -1, -1));

        jLabel1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel1.setText("DNI");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(139, 31));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel2.setText("BUSCAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("LISTA DE PACIENTES ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, -1, -1));

        jLabel4.setText("NOMBRES");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        nomb.setPreferredSize(new java.awt.Dimension(204, 35));
        nomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombActionPerformed(evt);
            }
        });
        jPanel1.add(nomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        ap.setPreferredSize(new java.awt.Dimension(204, 35));
        ap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apActionPerformed(evt);
            }
        });
        jPanel1.add(ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        jLabel5.setText("APELLIDO PATERNO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        am.setPreferredSize(new java.awt.Dimension(204, 35));
        am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amActionPerformed(evt);
            }
        });
        jPanel1.add(am, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        jLabel6.setText("APELLIDO MATERNO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, -1, -1));

        jLabel7.setText("DNI");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, -1, -1));

        dni_reg.setPreferredSize(new java.awt.Dimension(204, 35));
        jPanel1.add(dni_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, -1, -1));

        fn.setPreferredSize(new java.awt.Dimension(204, 35));
        jPanel1.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        jLabel8.setText("FECHA DE NACIMIENTO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        sexo.setPreferredSize(new java.awt.Dimension(204, 35));
        jPanel1.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, -1));

        jLabel9.setText("SEXO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, -1, -1));

        eps.setPreferredSize(new java.awt.Dimension(204, 35));
        jPanel1.add(eps, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jLabel10.setText("EPS");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        jLabel11.setText("TELÉFONO");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, -1));

        telef.setPreferredSize(new java.awt.Dimension(204, 35));
        jPanel1.add(telef, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

        hc.setPreferredSize(new java.awt.Dimension(204, 35));
        jPanel1.add(hc, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, -1, -1));

        jLabel12.setText("HISTORIA CLÍNICA");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel13.setText("DATOS PERSONALES");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setText("REGISTRAR");
        jButton1.setBorder(null);
        jButton1.setOpaque(true);
        jButton1.setPreferredSize(new java.awt.Dimension(139, 31));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 270, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel14.setText("PACIENTES");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setText("LIMPIAR");
        jButton2.setBorder(null);
        jButton2.setOpaque(true);
        jButton2.setPreferredSize(new java.awt.Dimension(139, 31));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 350, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(217, 217, 217));
        jSeparator1.setForeground(new java.awt.Color(217, 217, 217));
        jSeparator1.setPreferredSize(new java.awt.Dimension(1280, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, 1280, 30));

        botonRegresar_Recepcionist.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonRegresar_Recepcionist.setForeground(new java.awt.Color(41, 98, 255));
        botonRegresar_Recepcionist.setText("< REGRESAR");
        botonRegresar_Recepcionist.setBorder(null);
        botonRegresar_Recepcionist.setBorderPainted(false);
        botonRegresar_Recepcionist.setContentAreaFilled(false);
        botonRegresar_Recepcionist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresar_Recepcionist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegresar_RecepcionistMouseClicked(evt);
            }
        });
        botonRegresar_Recepcionist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresar_RecepcionistActionPerformed(evt);
            }
        });
        jPanel1.add(botonRegresar_Recepcionist, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 80, 30));

        TablaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "APELLIDO P", "APELLIDO M", "NOMBRES", "EPS", "NAC.", "GENERO", "TELEFONO"
            }
        ));
        jScrollPane2.setViewportView(TablaPacientes);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 1070, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dni_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dni_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dni_buscarActionPerformed

    private void apActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apActionPerformed

    private void amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        if (this.dni_buscar.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Uno o mas campos estan vacios. Favor de llenarlos.");

        } else {
            buscar(this.dni_buscar.getText());
        }

    }//GEN-LAST:event_jPanel2MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.nomb.setText("");
        this.am.setText("");
        this.ap.setText("");
        this.dni_reg.setText("");
        this.eps.setText("");
        this.fn.setText("");
        this.hc.setText("");
        this.dni_buscar.setText("");
        this.telef.setText("");
        this.sexo.setText("");

        mostrarpacientes();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            // TODO add your handling code here:
            registrar();
        } catch (SQLException ex) {
            Logger.getLogger(pacientes_interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void botonRegresar_RecepcionistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresar_RecepcionistMouseClicked
        this.dispose();
        new inicioRecepcionista().setVisible(true);
    }//GEN-LAST:event_botonRegresar_RecepcionistMouseClicked

    private void botonRegresar_RecepcionistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresar_RecepcionistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresar_RecepcionistActionPerformed

    private void nombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pacientes_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pacientes_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pacientes_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pacientes_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pacientes_interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaPacientes;
    private javax.swing.JTextField am;
    private javax.swing.JTextField ap;
    private javax.swing.JButton botonRegresar_Recepcionist;
    private javax.swing.JTextField dni_buscar;
    private javax.swing.JTextField dni_reg;
    private javax.swing.JTextField eps;
    private javax.swing.JTextField fn;
    private javax.swing.JTextField hc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nomb;
    private javax.swing.JTextField sexo;
    private javax.swing.JTextField telef;
    // End of variables declaration//GEN-END:variables
}
