/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InicioSesion;
import Citas.Citas;
import Pacientes.pacientes_interfaz;
import StaffMedico.Especialistas;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

import proyectoppc.Home;

/**
 *
 * @author Paula
 */
public class inicioRecepcionista extends javax.swing.JFrame {

    /**
     * Creates new form inicioAdministrativo
     */
    public inicioRecepcionista() {
        initComponents();
    }                                          

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        medicoLabel = new javax.swing.JLabel();
        citaLabel = new javax.swing.JLabel();
        salirLabel = new javax.swing.JLabel();
        pacienteLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(1280, 645));
        background.setRequestFocusEnabled(false);
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.jpg"))); // NOI18N
        logo.setText("jLabel1");
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 293, -1));

        medicoLabel.setBackground(new java.awt.Color(255, 255, 255));
        medicoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medicoLabel.setText("STAFF MÉDICO");
        medicoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        medicoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        medicoLabel.setMaximumSize(new java.awt.Dimension(198, 35));
        medicoLabel.setMinimumSize(new java.awt.Dimension(198, 35));
        medicoLabel.setName(""); // NOI18N
        medicoLabel.setPreferredSize(new java.awt.Dimension(198, 35));
        medicoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medicoLabelMouseClicked(evt);
            }
        });
        background.add(medicoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 280, -1, -1));

        citaLabel.setBackground(new java.awt.Color(255, 255, 255));
        citaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        citaLabel.setText("CITA");
        citaLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        citaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        citaLabel.setMaximumSize(new java.awt.Dimension(198, 35));
        citaLabel.setMinimumSize(new java.awt.Dimension(198, 35));
        citaLabel.setName(""); // NOI18N
        citaLabel.setPreferredSize(new java.awt.Dimension(198, 35));
        citaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                citaLabelMouseClicked(evt);
            }
        });
        background.add(citaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 376, -1, -1));

        salirLabel.setBackground(new java.awt.Color(255, 255, 255));
        salirLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salirLabel.setText("SALIR");
        salirLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        salirLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirLabel.setMaximumSize(new java.awt.Dimension(198, 35));
        salirLabel.setMinimumSize(new java.awt.Dimension(198, 35));
        salirLabel.setName(""); // NOI18N
        salirLabel.setPreferredSize(new java.awt.Dimension(198, 35));
        salirLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirLabelMouseClicked(evt);
            }
        });
        background.add(salirLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 424, -1, -1));

        pacienteLabel.setBackground(new java.awt.Color(255, 255, 255));
        pacienteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pacienteLabel.setText("PACIENTES");
        pacienteLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pacienteLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pacienteLabel.setMaximumSize(new java.awt.Dimension(198, 35));
        pacienteLabel.setMinimumSize(new java.awt.Dimension(198, 35));
        pacienteLabel.setName(""); // NOI18N
        pacienteLabel.setPreferredSize(new java.awt.Dimension(198, 35));
        pacienteLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pacienteLabelMouseClicked(evt);
            }
        });
        background.add(pacienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 328, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void medicoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicoLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        try {
            new Especialistas().setVisible(true);
        } catch (RemoteException ex) {
            Logger.getLogger(inicioRecepcionista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_medicoLabelMouseClicked

    private void citaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_citaLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Citas().setVisible(true);
    }//GEN-LAST:event_citaLabelMouseClicked

    private void salirLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirLabelMouseClicked
        // TODO add your handling code here:
         this.dispose();
        new Home().setVisible(true);
        System.out.println("Cerrando Sesión");
    }//GEN-LAST:event_salirLabelMouseClicked

    private void pacienteLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pacienteLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new pacientes_interfaz().setVisible(true);
    }//GEN-LAST:event_pacienteLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicioRecepcionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel citaLabel;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel medicoLabel;
    private javax.swing.JLabel pacienteLabel;
    private javax.swing.JLabel salirLabel;
    // End of variables declaration//GEN-END:variables
}
